CREATE TABLE users(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    first_name VARCHAR(300) NOT NULL,
    last_name VARCHAR(300) NOT NULL,
    email VARCHAR(400) NOT NULL UNIQUE,
    phone VARCHAR(300),
    password VARCHAR(1000) NOT NULL
);